
install.packages(c("alr3","corrplot","GGally","psych","caret","lattice","ggplot2" ))
library(e1071)
library(alr3)
library(corrplot)
library(GGally)
library(psych)
library(caret)
library(lattice)
library(ggplot2)
 data()
head(cars) 
